### PR TITLE
Toolchain update

### PR DESCRIPTION
**Pull request by mhkabir**
Companion PR to https://github.com/PX4/Firmware/pull/6528

### CODE REVIEW

**Comment by julianoes** [comment]
@mhkabir does this need any other changes to go with it?

**Comment by mhkabir** [comment]
@julianoes yes, it needs a documentation update and users to change to the new toolchain installer from here : 

Basically, purge the old toolchain from /opt/rpi_toolchain, remove the old definition of "RPI_TOOLCHAIN_DIR" from their env and use the new installer from here : https://github.com/PX4/Toolchains

Do you think I should add a optional "clean" argument to the new installer which will nuke the old toolchain before installing the new one?

**Comment by julianoes** [comment]
Ok, can you please add the needed docs.

> Do you think I should add a optional "clean" argument to the new installer which will nuke the old toolchain before installing the new one?

Sure, sounds like a good thing.

**Comment by mhkabir** [comment]
Ok, I've added the cleaning argument. The script still needs some more polishing to detect existing new-version installs from itself and optionally upgrade those.

I'll ping here once that's done and then we can merge the PX4 side. The docs update will come last, once the Firmware PR and this PR is merged.

**Comment by julianoes** [comment]
@mhkabir what's the state?

@bkueng have you seen this?

**Pull request closed without merging**
