### PR TITLE
Snapdragon Flight power module

### PR DESCRIPTION
**Pull request by ChristophTobler**
I added the LTC2946 driver (power module for the Snapdragon Flight). The files already existed but were removed (not sure why) and I added some minor modifications.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
What is the testing level on this?

**Comment by ChristophTobler** [comment]
I tested it with a power supply.

**Comment by LorenzMeier** [comment]
Cool - can you fix Travis? Thanks!

**Comment by ChristophTobler** [comment]
Yup, I'm on it.

**Comment by ChristophTobler** [comment]
This time there's an error with Homebrew. Seems to need an update.
```
/usr/local/Homebrew/Library/Homebrew/brew.rb:12:in `<main>': Homebrew must be run under Ruby 2.3! You're running 2.0.0. (RuntimeError)
```

**Comment by ChristophTobler** [comment]
@LorenzMeier I fixed Travis

**Pull request merged**
