### PR TITLE
MPU9250, BMP280, HMC5j883 bringup

### PR DESCRIPTION
**Pull request by julianoes**
Unit tests of BMP280 and MPU9250 drivers are running

**Steps to reproduce**

Build and load:
```
make
cd build_qurt
make df_pressure_test_app-load
make df_pressure_test-load
make df_testapp_app-load
make df_testapp-load
make libdf_pressure_test-load
make libdf_testapp-load
make df_imu_test-load
make df_imu_test_app-load
make df_mag_test-load
make libdf_mag_test-load
```

Then attach the mini-dm for the adsp printfs:
```
$HOME/Qualcomm/Hexagon_SDK/2.0/tools/mini-dm/Linux_Debug/mini-dm
```

Run the tests, attached with screen on 115200:
```
cd /home/linaro
./df_imu_test_app
./df_pressure_test_app
./df_mag_test_app
```

### CODE REVIEW

**Comment by mhkabir** [comment]
@julianoes What's the status on this one? Is this at a stage where register dumping works?

**Comment by julianoes** [comment]
The last time I played with it last week, the WHOAMI readReg lead to a crash. There have been changes in the aDSP image since and @mcharleb might give it another try soon.

**Comment by mhkabir** [comment]
@julianoes Would you be able to help me get to a similar stage on normal Linux hardware (e.g RPi) where I can run the DriverFramework unit tests? This would be a part of https://github.com/PX4/Firmware/issues/3509
I'm sure this would speed up development for DF in general as well, as it would be much more accessible compared to running on the Qualcomm aDSP. Very few people have Snapdragon hardware.

Let me know what needs to be done. Thanks!

**Comment by julianoes** [comment]
Quick update: MPU9250 and BMP280 unit tests are working now.

**Comment by bo-rc** [comment]
@julianoes Thanks for your great work! 
Can i ask a question, which is related to @mhkabir 's previous post, is it possible now that we can test MPU9250 on Rpi2 and Navio board?

Thank you!!

**Comment by mhkabir** [comment]
@bo-rc No, not yet.

**Comment by julianoes** [comment]
@bo-rc @mhkabir thanks that would be nice to collaborate on this. Give me another day to get this running with the Snapdragon first, then I can have a look how that could work on the RPi.

**Comment by mhkabir** [comment]
Thanks, that'd be awesome!

**Comment by bo-rc** [comment]
Thank you!
I'm looking forward to it!

**Comment by julianoes** [comment]
@mcharleb The recent build changes have broken the standalone building of the unit tests. It would be good if you could fix this.

**Comment by mcharleb** [comment]
@julianoes If you run make at the top level of DriverFramework it should build all the unit tests

**Comment by LorenzMeier** [comment]
@julianoes Can we get this reviewed and in?

**Comment by julianoes** [comment]
The mag is not functional yet because of #23 and #22. I would say let's merge it when integration4 goes into master on the Firmware side.

**Pull request merged**
