### PR TITLE
Lock refactoring

### PR DESCRIPTION
**Pull request by mcharleb**
Fixes for locking, unprotected data access, and better modularization of the code. This PR contains critical fixes for DF running on Linux. It still needs to be tested on other platforms.

### CODE REVIEW

**Comment by mcharleb** [comment]
@LorenzMeier This passed the extended unit tests on OSX and Linux. It is ready to merge. Then I can test it with PX4.

**Comment by LorenzMeier** [comment]
Thanks! I've merged it. @julianoes Please assist with the PX4 integration and merging. Thanks!

**Comment by julianoes** [comment]
Thanks @mcharleb. I'll test this on Eagle next week when I'm back.

**Comment by julianoes** [comment]
Since this is on master and I've done bench tests with this it seems to be good, thanks!

**Pull request merged**
