### PR TITLE
Mark updates

### PR DESCRIPTION
**Pull request by mcharleb**
Converted WorkHandle to a managed handle

### CODE REVIEW

**Comment by mcharleb** [comment]
What is different between first and second CI tests? They boath seem to be clang-3.4 and Ubuntu 12.04

**Comment by dagar** [comment]
The first build is your mark_updates branch merged with current master, the second is the mark_updates branch as is.

**Comment by mcharleb** [comment]
@dagar I actually meant in the first CI test, there are 3 test run. Two are Linux Ubuntu 12.04 and the other is MacOS. What is the difference between the two Linux tests? They seem to be identically configured, but the second one segfaults.

**Comment by mcharleb** [comment]
@LorenzMeier I can't reproduce these segfaults on my Ubuntu 15.04 machine

**Comment by LorenzMeier** [comment]
All three build instances failed with a segfault or timeout (endless loop on Mac Os). Could you please try this in a 14.04 VM?

**Comment by mcharleb** [comment]
@LorenzMeier All checks pass! Finally!

**Comment by LorenzMeier** [comment]
Nice!

**Pull request merged**
