### PR TITLE
Support using DriverFramework as a PX4 module

### PR DESCRIPTION
**Pull request by mcharleb**
PX4 can now include src/lib/DriverFramework/framework in the list
of modules for a target.

Signed-off-by: Mark Charlebois <charlebm@gmail.com>

### CODE REVIEW

**Comment by davids5** [comment]
@mcharleb 

What about the DF_TARGET and -D__DF_NUTTX?

**Comment by mcharleb** [comment]
@davids5 I did an overhaul of the DF_TARGET handling. Its now removed from PX4.

**Comment by mcharleb** [comment]
@LorenzMeier The CI test failed due to network error

**Comment by julianoes** [comment]
That was quick. @LorenzMeier did you test it all?

**Comment by LorenzMeier** [comment]
No I didn't, but I'm sure Mark has and it would be good if you could re-eval on target. This is blocking a number of critical things for David so we need to get this in.

**Comment by julianoes** [comment]
I understand, still I'd vote for test first instead of merge and then test and fix and merge again :).

**Comment by julianoes** [comment]
Let me start digging:

```
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:136:failed to create tls key/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:112:listener using ion heap: -1
ERROR Initialize Error calling the uorb fastrpc initalize method..

WARN  mode: 0, data rate: 1000000 B/s on udp port 14556
WARN  offboard mission init: ERROR
WARN  getting required buffer size failed
INFO  Setting up UDP w/port 14556

WARN  no broadcasting address found
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:129:listener protocol failure -1
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:133::error: -1: 0 == (nErr = __QAIC_HEADER(adsp_listener_next_invoke)( ctx, nErr, 0, 0, &ctx, &handle, &sc, bufs->inbufs, inBufsAllocated, bufs->inbufLenReqs, MAX_BUFS, bufs->outbufLenReqs, MAX_BUFS))
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:192:listener thread exiting with code -1
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:224::error: -1: 0 == (nErr = remotectl_open(name, (int*)ph, dlerrstr, sizeof(dlerrstr), &dlerr))
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/listener_android.c:194:listener thread failed to cleanly shutdown.  This is ok durring process exit.
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:224::error: -1: 0 == (nErr = remotectl_open(name, (int*)ph, dlerrstr, sizeof(dlerrstr), &dlerr))
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:224::error: -1: 0 == (nErr = remotectl_open(name, (int*)ph, dlerrstr, sizeof(dlerrstr), &dlerr))
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:224::error: -1: 0 == (nErr = remotectl_open(name, (int*)ph, dlerrstr, sizeof(dlerrstr), &dlerr))
/home/cberg/Desktop/r00015/oe-core/build/tmp-eglibc/work/cortexa8hf-vfp-neon-linux-gnueabi/adsprpc/1.0-r0/adsprpc-1.0/src/fastrpc_apps_user.c:224::error: -1: 0 == (nErr = remotectl_open(name, (int*)ph, dlerrstr, sizeof(dlerrstr), &dlerr))
ERROR ERROR: FastRpcWrapper Not Initialized
```

**Comment by LorenzMeier** [comment]
Understood. I squashed the commit so worst case its a quick revert.

**Comment by LorenzMeier** [comment]
@mcharleb I would appreciate if you could ramp up your internal QA so that we don't have PRs immediately exploding on us. That should by default include running what you propose on an Eagle board using our build and tools.

**Comment by julianoes** [comment]
@LorenzMeier: I was in touch with @mcharleb and my next thing was to test it :).

**Comment by LorenzMeier** [comment]
PRs in that shape should be clearly marked WIP. @mcharleb You have your client to default to adding "signed off by" - that shouldn't be there neither since it implies its a) finished and b) you're vouching for it.

Thanks!

**Comment by julianoes** [comment]
@LorenzMeier, @mcharleb: It looks like the crash is not due to this change here but it broke earlier, see https://github.com/PX4/Firmware/issues/4421.

**Comment by mcharleb** [comment]
@Lorenz What was not QA in the PR I gave you?

**Comment by julianoes** [comment]
Sorry @mcharleb your fix worked, thanks for that.

The crash came from somewhere else. I should have done the bisecting before commenting on this thread. I was a bit annoyed that it got merged without testing from my side which I was about to do.

**Pull request merged**
