### PR TITLE
Pr bebop thrust

### PR DESCRIPTION
**Pull request by tumbili**
Did a test flight which went well. I need to test more and make sure the logging works.
The goal is to have motor rpm and desired rpm logged.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@ChristophTobler @eyeam3 Please review - help testing.

**Comment by ChristophTobler** [comment]
@tumbili We went out testing today. The logs are here: http://logs.px4.io/plot_app?log=efa22db1-32e7-4866-a24d-dd13d0d474e2 http://logs.px4.io/plot_app?log=922eed83-897a-4d6b-bc53-c7cf1e3aa219

We changed these parameters
```
MC_ROLLRATE_P 0.06
MC_PITCHRATE_P 0.07
MC_YAWRATE_P 0.05
```

Flight was ok (very windy and cold). There seems to be something with the height though. Also with auto takeoff: it went up like 5m and then down to maybe 1.5m

**Comment by tumbili** [comment]
@ChristophTobler @LorenzMeier @eyeam3 From a quick look at the log I would say that the accel calibration is not working or is not applied correctly. The acceleration measured in z direction seems too low which could make the estimator think that it's climbing and therefore, the controller makes the vehicle descent. Also I noticed that this behavior improves during flight which is likely due to the accel bias catching up.

**Comment by ChristophTobler** [comment]
@tumbili I think it is almost impossible to screw up z-axis accel calibration since you just have to put the quad on the ground ;) But yes, that sounds reasonable.

**Pull request merged**
