### PR TITLE
Add Support for Aerotenna OcPoC Hardware

### PR DESCRIPTION
**Pull request by davidaroyer**
This PR introduces necessary changes to support the Aerotenna OcPoC flight controller.

Aside from device path changes, we ran into issues with the MS5611 baro when we first switched to using it in SPI mode - the baro would return nothing for temperature and pressure. The issue is fixed with the addition of a new SPIDevObj function which is currently only applied for OcPoC (see commits 427e654 and 2d5ea38).

### CODE REVIEW

**Comment by davidaroyer** [comment]
I suppose I can use something like a BARO_USE_SPI for the SPI specific changes in the MS5611 driver, if that sounds acceptable. Are you alright with the board specific ifdef for the device path changes?

I've only been using this with Firmware.

**Comment by julianoes** [comment]
> Are you alright with the board specific ifdef for the device path changes?

I think so, yes.

**Comment by davidaroyer** [comment]
@julianoes, for the sake of completeness, I also tried to add a makefile for the board, but it has troubles with the BMP280 driver. It seems the sensor supports an SPI interface, but I don't have that sensor to test any changes. I could resolve the issue with an ifdef to leave out the BMP280 driver for either BARO_USE_SPI (which I think would be misleading) or for the __DF_OCPOC ifdef.

As I said earlier, I'm only using DriverFramework within Firmware, so it doesn't really make a difference to me whether or not the makefile is in there for OCPOC. However, I'm more than happy to add it if you'd prefer.

**Comment by julianoes** [comment]
Changes look good. For the Makefile, could you do it in a way similar to this maybe?
https://github.com/PX4/DriverFramework/blob/master/drivers/ms5611/test/CMakeLists.txt#L36

**Comment by davidaroyer** [comment]
@julianoes, I don't know why I didn't think of that before, but that worked fine.

**Comment by julianoes** [comment]
@davidaroyer sorry for not getting back to you here. It looks like CI failed. Can you please fix the style issues with:
```
make fix-style
```

**Comment by julianoes** [comment]
Still not happy somehow :(:

```
Formatted  ./framework/include/DevObj.hpp
./framework/include/DevObj.hpp bad formatting
Formatted  ./framework/src/DFList.cpp
./framework/src/DFList.cpp bad formatting
```

**Comment by davidaroyer** [comment]
@julianoes Apologies for my ignorance, but I can't seem to replicate the formatting issue. Both check-style and fix-style do nothing for me at this point, and the two files CI has pointed to are unrelated to the changes I've made in this pull request. Do you know something offhand that might cause this discrepancy?

**Comment by julianoes** [comment]
Haha, sorry it was that painful :smile:.

Thanks for the PR. I'll merge it for now.

@jywilson and @mcharleb had some ideas how to refactor the device interfaces to better handle cases with different buses like this one in the future and avoid some of the ifdefs.

**Pull request merged**
