### PR TITLE
Critical fixes for QuRT build

### PR DESCRIPTION
**Pull request by mcharleb**
QuRT C++ compiler does not support static initialization of classes.

Code was refactored to remove static C++ initialization

Signed-off-by: Mark Charlebois <charlebm@gmail.com>

### CODE REVIEW

**Comment by mcharleb** [comment]
@LorenzMeier Please make this a high priority to merge. The qurt build is broken without it. I would like to see the qurt_eagle_travis build added back to the CI look to catch future qurt breakage.

**Comment by LorenzMeier** [comment]
Sorry, missed that. Can you send a PR against upstream PX4 to switch the PX4 submodule?

**Comment by LorenzMeier** [comment]
Rebased and applied.

**Comment by mcharleb** [comment]
@LorenzMeier See https://github.com/PX4/Firmware/pull/4592

**Pull request closed without merging**
