### PR TITLE
Mark updates

### PR DESCRIPTION
**Pull request by mcharleb**
Making pull request so I can debug the issue on MacOS

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Output on my local machine:
```
test PASSED (60)
In while
TEST 6: Read after setSampleInterval
In while
schedule
In while
schedule 2
In while
schedule 3
In while
start
In while 2
DevObj::start
In while
DevObj::start 2
In while 2
reading
In while
timed out 60
In while 2
test FAILED (60)
In while
DevObj::removeHandle (0x7fff5f79e4a8)
In while 2
DevObj::stop
In while
tests done
In while
DevObj::stop
In while
shutdown
In while
```

**Comment by LorenzMeier** [comment]
The test returns 0 even on failure.

**Comment by LorenzMeier** [comment]
Can you fix the test logic to return 1 on failure? I will fix the error code handling.

**Comment by LorenzMeier** [comment]
I pushed a patch to convert errno to string. Its the timeout, yes.

**Comment by LorenzMeier** [comment]
Output:
```
timed out: Operation timed out (ret: 60)
waiting for work (10000000)
test PASSED (60)
HRTWorkQueue::process In while
TEST 6: Read after setSampleInterval
waiting for work (10000000)
schedule
HRTWorkQueue::process In while
schedule 2
waiting for work (10000000)
schedule 3
HRTWorkQueue::process In while
start
HRTWorkQueue::process work exists
DevObj::start
waiting for work (84)
DevObj::start 2
HRTWorkQueue::process In while
reading
HRTWorkQueue::process work exists
waiting for work (37)
HRTWorkQueue::process In while
HRTWorkQueue::process work exists
waiting for work (31)
HRTWorkQueue::process In while
HRTWorkQueue::process work exists
waiting for work (27)
HRTWorkQueue::process In while
timed out: Operation timed out (ret: 60)
HRTWorkQueue::process work exists
test FAILED (60)
waiting for work (12)
DevObj::removeHandle (0x7fff56c1e4a8)
HRTWorkQueue::process In while
DevObj::stop
HRTWorkQueue::process work exists
HRTWorkQueue::process do work (0x108fefb30)
DevObj::measure
DevObj::updateNotify
tests done
HRTWorkQueue::process work exists
DevObj::stop
waiting for work (72)
shutdown
HRTWorkQueue::process In while
waiting for work (10000000)
```

**Comment by mcharleb** [comment]
@LorenzMeier Fixed. The clock_gettime() implementation for the OSX build was no bueno.

**Comment by LorenzMeier** [comment]
Fixing the same thing in the current codebase improved things, but it didn't fix SITL entirely. What are the next steps to get closer to rebase SITL on this effort?

**Comment by mcharleb** [comment]
Now that its solid on all platforms I'll push a dev branch for driver_framework to  PX4 and continue integrating the drivers.

**Pull request merged**
