### PR TITLE
make num_read_attempts a command-line parameter

### PR DESCRIPTION
**Pull request by ericye16**

### CODE REVIEW

**Comment by julianoes** [comment]
@ericye16 thanks for the PR. This is very useful.

Can you please fix the style issues?
https://travis-ci.org/PX4/DriverFramework/jobs/144613671#L272
`make fix-style`

**Comment by ericye16** [comment]
When I run it, it touches a bunch of files that weren't changed in my commit. Should I add those changes as well?

**Comment by julianoes** [comment]
@ericye16 strange, even when you rebase on latest origin/master?

**Comment by julianoes** [comment]
Do you have the correct astyle version?

**Comment by ericye16** [comment]
astyle --version
Artistic Style Version 2.03

And yes, I'm rebased on origin/master.

**Comment by ericye16** [comment]
I'm running this command at the root of this repository. Is that correct? Where does astylerc come from?

**Comment by ericye16** [comment]
What version of astyle are you using? For some reason mine incorrectly formatting properly-formatted code.

**Comment by ericye16** [comment]
>9404 waitSignal() timeout of 5000us was 9032us
>9417 TEST waitSignal() timeout: FAILED 

I don't think this was caused by my change...

**Comment by julianoes** [comment]
@ericye16 Thanks for the fixes, I'm just re-running the Mac travis tests, and I expect it to go through this time.

**Comment by julianoes** [comment]
Cross-tested on my Snappy, rebased and applied. Thank you!

**Pull request closed without merging**
