### PR TITLE
driver framework: mpu6050 activate imu dlpf (set to 44 Hz cutoff)

### PR DESCRIPTION
**Pull request by tumbili**
- this improves flight performance very much

Signed-off-by: Roman <bapstroman@gmail.com>

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Looks good.

**Comment by tumbili** [comment]
@LorenzMeier It would be nice if we could activate this in the other drivers as well and test with Snapdragon.
I think they also don't have the DLPF activated.

**Comment by LorenzMeier** [comment]
Filed here so we don't forget: https://github.com/PX4/DriverFramework/issues/164

**Comment by jywilson** [comment]
@tumbili You are correct, we do not use the DLPF.  We always assumed that the flight stack would do a better job of filtering.  

You might consider making the use of DLPF a startup option, just in case the IMU data is used with other algorithms that need raw, unfiltered data.

**Pull request merged**
