### PR TITLE
Alow the driver framework to not be included for bootloaders

### PR DESCRIPTION
**Pull request by davids5**
This solves the problem but it would be much better to the df added like all other components, from top level inclusion in cmake/configs/*cmake files that need it

### CODE REVIEW

**Comment by julianoes** [comment]
I think I understand the problem but of course I'd prefer it to be fixed in PX4/Firmware as you describe in https://github.com/PX4/Firmware/issues/4388.

@davids5 Do you need this urgent as a workaround for now?

**Comment by davids5** [comment]
@julianoes  it is not urgent - I have the work around in this PR that should not have any negative affects. It is however a kluge. I raised the issue because the PX4 cmake system has very well defined patterns for inclusion and they were not followed by the DF. Thus making exclusion of the DF difficult it takes more than just not including a reference in say px4esc-v1_bootloader.camke 

The goal is to have the a cmake file in the DF lib that is referenced from the top level targets in /cmake/configs/*.cmake that need the library, You may want to discuss this with @jgoppert as he the architect of the PX4 cmake.

**Comment by mcharleb** [comment]
@davids5 Hi David, perhaps I just was not aware of the "defined patterns for inclusion" to use for PX4. Can you help me understand what they are? I'm happy to refactor so things are cleaner.

**Comment by davids5** [comment]
@mcharleb - yes - perhaps it is not obvious, Sorry I assumed it was,  I guess I see the pattern because I had port nuttx_next to cmake and touch all the new targets.

In looking  at https://github.com/PX4/Firmware/blob/nuttx_next_cmake/cmake/configs/nuttx_px4fmu-v2_default.cmake

uavcan is an external library https://github.com/PX4/Firmware/blob/nuttx_next_cmake/cmake/configs/nuttx_px4fmu-v2_default.cmake#L180-L183

 and there is a section for libraries 

https://github.com/PX4/Firmware/blob/nuttx_next_cmake/cmake/configs/nuttx_px4fmu-v2_default.cmake#L116-L118

I think either approach should work. 

The goal would be to not have the DF assumed to always be in a target configuration.

**Comment by mcharleb** [comment]
@davids5 Thanks for the explanation. I guess my assumption at the time was that even NuttX builds would evolve to use DF over time, but implementing it as a lib in the latter example your pointed to above seems like a cleaner implementation. I'll try to clean it up. Thanks.

**Comment by LorenzMeier** [comment]
@mcharleb So get this PR in and you'll clean up or will you provide a cleanup quickly?

**Comment by mcharleb** [comment]
@LorenzMeier I'll try to get a fix done today and make a PR.

**Comment by mcharleb** [comment]
@LorenzMeier The issue should be fixed by https://github.com/PX4/Firmware/pull/4414

**Comment by mcharleb** [comment]
@LorenzMeier The DriverFramework changes are in https://github.com/PX4/DriverFramework/pull/67

The corresponding Firmware changes are to follow.

**Comment by mcharleb** [comment]
@LorenzMeier Here is the corresponding Firmware PR: https://github.com/PX4/Firmware/pull/4415

@davids5 Can you please tell me which NuttX configs need to include lib/DriverFramework/framework?

**Comment by julianoes** [comment]
@davids5 is this still needed after #67?

**Comment by davids5** [comment]
@julianoes and @mcharleb  - Thank you for getting this in. 

I have branches that are pointed to this commit. Once I test on the master with https://github.com/PX4/DriverFramework/pull/67 I will close the PR.

**Comment by LorenzMeier** [comment]
@davids5 Did you end up testing with master?

**Comment by LorenzMeier** [comment]
@davids5 Ping.

**Comment by davids5** [comment]
This was needed for nuttx_v3 and yes it was tested on nuttx_v3 with a master merge

**Comment by julianoes** [comment]
@davids5 ok to delete the branch?

**Pull request closed without merging**
