### PR TITLE
Adds LSM9DS1 IMU Sensor for Navio2

### PR DESCRIPTION
**Pull request by mayanez**
Related to Issue https://github.com/PX4/DriverFramework/issues/44
Related PR: https://github.com/PX4/Firmware/pull/4888
Adds LSM9DS1 support with Mag for Navio2.

Verified and tested on RPi3 with Navio2.

### CODE REVIEW

**Comment by LorenzMeier** [comment]
Nice! Could you have a look at the CI error? What is the testing state of this?

**Comment by mayanez** [comment]
It looks like the CI error is related to a #if defined(__RPI2) block for the SPI device paths. I've changed them to default to "". Is there a convention that is being followed for setting these defaults?

**Comment by LorenzMeier** [comment]
I don't think we have a strong convention yet. Suggestions welcome.

**Comment by mayanez** [comment]
Alright. Looks like the CI is also building on OS X so need a special #if there as well. I'll see what convention makes the most sense at the moment in terms of the different environments and modify the PR.

**Pull request closed without merging**
