### PR TITLE
MS5611 driver for RPi (rebased)

### PR DESCRIPTION
**Pull request by julianoes**
Based on #111.

### CODE REVIEW

**Comment by julianoes** [comment]
@mayanez: the unit test doesn't succeed yet on my RPi2/Navio2.

```
./df_ms5611_test 
18446744073709551607 Entering: run
86 WARNING: setRealtimeSched failed (not run as root?)
439 Unable to reset device: -1
475 error: unable to communicate with the MS5611 pressure sensor
505 error: pressure sensor initialization failed, sensor read thread not started
```

**Comment by julianoes** [comment]
Got the unit test to work. It turns out that only the very first I2C write after a power cycle failed. I added a retry functionality which fixed it.

Additionally, I cleaned up the I2C interfaces and removed `_transfer()` which was added recently but could actually be accomplished by just using the existing `readReg()` and `writeReg()` which makes it easier when having to support different operating systems.

**Comment by LorenzMeier** [comment]
CI fails.

**Comment by julianoes** [comment]
I see that :)
It's a bit of a mess with `__LINUX` on Mac which then wants to include i2c headers for Linux.

**Pull request merged**
