### PR TITLE
add build edison

### PR DESCRIPTION
**Pull request by AD-Aleksandrov**

### CODE REVIEW

**Comment by AD-Aleksandrov** [comment]
edison spi interface is similar on rpi, but mpu9250 doesnt work correctly on edison, i commented it inside code

**Comment by AD-Aleksandrov** [comment]
edison and rpi spi interfaces are similar, i fixed something and commented inside the code

**Comment by julianoes** [comment]
@AD-Aleksandrov Thanks for the PR, appreciated! 

Could you please run `make fix-style`?

**Comment by AD-Aleksandrov** [comment]
I apologize for my stupidity:)

**Comment by julianoes** [comment]
Hehe, no worries :). Let's see if travis is happy this time.

**Comment by AD-Aleksandrov** [comment]
he cannot start

**Comment by julianoes** [comment]
Rebased and applied, thank you!

**Pull request closed without merging**
